//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_SQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avatar> Avatar { get; set; }
        public virtual DbSet<Clothes> Clothes { get; set; }
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<UserMaterial> UserMaterial { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersService> UsersService { get; set; }
        public virtual DbSet<Washhouse> Washhouse { get; set; }
    }
}
