//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaterial
    {
        public int id { get; set; }
        public int id_user { get; set; }
        public int id_material { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Washhouse Washhouse { get; set; }
    }
}
